apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo $MY_USER, Kubernetes! && sleep 3600"]
    env:
    - name: MY_USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: user