apiVersion: v1
kind: Pod
metadata: 
  name: pod-conf-map-ref
spec:
  containers:
    - name: cont1
      image: busybox
      command: ['sh','-c', "echo $(MY_VAR) && sleep 3600"]
      env:
       - name: MY_VAR
         valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: key1
