apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: web
spec:
  containers:
  - name: nginx-p
    image: nginx
    command: ["nginx"]
    args: ["-g", "daemon off;" ,"-q"]
    ports:
      - containerPort: 80