apiVersion: v1
kind: Pod
metadata: 
  name: candy-service
spec:
  serviceAccountName: candy-svc
  securityContext:
    fsGroup: 2000
  volumes:
    - name: candy-service-volume
      configMap:
        name: candy-service-config
  containers:
    - name: candy-service-container
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASSWORD
      volumeMounts:
        - name: candy-service-volume
          mountPath: /etc/config
      image: linuxacademycontent/candy-service:1
      resources:
        requests: 
          cpu: 250m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi