apiVersion: v1
kind: Pod
metadata:
  name: my-securitycontext-pod
spec:
# Make sure that the below configuration is present in all the kubernetes worker nodes (minions)
# sudo useradd -u 2000 container-user
# sudo groupadd -g 3000 container-group
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo Hello Kubernetes! && sleep 3600"]